name: fomet_app
description: "Official application of the Fomet SpA company."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.2.3

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
    
  flutter_svg: ^2.0.9
  
  flutter_web_plugins:
    sdk: flutter

  fomet_ui:
    path: packages/fomet_ui
  
  go_router: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  generate: true
  
  assets:
    - assets/svg/
