name: fomet_api_client
description: The HTTP client of the FometApp application.
version: 1.0.0

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.1.2
  xml: ^6.5.0

dev_dependencies:
  test: ^1.25.0
