/// An example of a valid XML response about product information.
const productInfoTestResponse = '''
<DettaglioArticolo xmlns="http://schemas.datacontract.org/2004/07/FometAppService.CArticolo" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
    <DettArticolo>
        <item>
            <Nome>Codart</Nome>
            <value>AKER/BB</value>
        </item>
        <item>
            <Nome>Descrizione</Nome>
            <value>desc</value>
        </item>
        <item>
            <Nome>Descrizione2</Nome>
            <value/>
        </item>
        <item>
            <Nome>Descrizione3</Nome>
            <value/>
        </item>
        <item>
            <Nome>Descrizione4</Nome>
            <value/>
        </item>
        <item>
            <Nome>Immagine</Nome>
            <value>image</value>
        </item>
        <item>
            <Nome>CodVarieta</Nome>
            <value>ACT</value>
        </item>
        <item>
            <Nome>Applicazione_Fogliare</Nome>
            <value>No</value>
        </item>
        <item>
            <Nome>FertAutunnale</Nome>
            <value>autumn</value>
        </item>
        <item>
            <Nome>FertPrimaverile</Nome>
            <value>spring</value>
        </item>
        <item>
            <Nome>FertSuFila</Nome>
            <value>row</value>
        </item>
        <item>
            <Nome>FertCopertura</Nome>
            <value>coverage</value>
        </item>
        <item>
            <Nome>FertIrrigazione</Nome>
            <value>irrigation</value>
        </item>
        <item>
            <Nome>FertPresemina</Nome>
            <value>presowing</value>
        </item>
        <item>
            <Nome>Attenzione</Nome>
            <value>warning</value>
        </item>
        <item>
            <Nome>note</Nome>
            <value>notes</value>
        </item>
    </DettArticolo>
</DettaglioArticolo>
''';
