name: flutter_web_deploy

on:
  push:
    branches:
      - main

jobs:
  flutter_web_deployment:
    name: Flutter web deployment
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.4'
          channel: 'stable'

      - name: Installing dependencies
        run: flutter pub get

      - name: Building for the web
        run: flutter build web --csp

      - name: Setting the git username
        run: git config user.name github-actions

      - name: Setting the git email
        run: git config user.email github-actions@github.com

      - name: Adding web source
        run: git --work-tree build/web add --all

      - name: Adding a commit message
        run: git commit -m "Automatic deployment by github-actions"

      - name: Automatic web deployment
        run: git push origin HEAD:web_deployment --force